### PR TITLE
BossBar

### PR DESCRIPTION
**Pull request by QueryPE**
## PR Description
Adds simple boss bar functions, not 100% sure how to update the health yet 

## Have you tested it?
- [x] I have tested it.
- [ ] I have not tested it.
...

### CODE REVIEW

**Comment by QueryPE** [comment]
Seems like a bad method idk tho

**Comment by Nought57** [comment]
Thanks! Merge it!

**Comment by QueryPE** [comment]
@Nought57 do you think I can be a collaborator

**Comment by Nought57** [comment]
@QueryPE I sent an invitation card! Please help!

**Comment by QueryPE** [comment]
@Nought57 thank you :)

**Pull request merged**
